### DISCUSSION TITLE
Filter not displaying ?

### DISCUSSION THREAD

**Discussion by Peepingtom** [Kreyu/data-table-bundle#179] [Q&A] [answered]
Hello.

I'm tried to add a filter to my data-table, but all I got is the "filter" icon

![image](https://github.com/user-attachments/assets/1b5fb9f6-7d02-454f-ba2c-34403640cd7c)

Here is how I implemented my datatable

![image](https://github.com/user-attachments/assets/3d772607-8a2d-452b-9a42-77a334b25af2)

am I missing something :( ?

**Comment by davidnectarestudio** [comment]
Did you click on filter icon?

**Comment by davidnectarestudio** [comment]
Check if you have some missing configuration values here

```yaml
# config/packages/kreyu_data_table.yaml
kreyu_data_table:
    defaults:
        pagination:
            enabled: true
            persistence_enabled: true
            per_page_choices: [25, 50, 100, 200]
        sorting:
            enabled: true
            persistence_enabled: true
        filtration:
            enabled: true
            persistence_enabled: true
        exporting:
            enabled: true
```

**Reply by Peepingtom** [reply]
Thank you for your answer.

I tried to click on it, nothing happens

my config yaml 

```
# config/packages/kreyu_data_table.yaml
kreyu_data_table:
    defaults:
        themes:
            - '@KreyuDataTable/themes/bootstrap_5.html.twig'
        filtration:
            enabled: true
```

My controller
```
public function index(EntityManagerInterface $entityManager, Request $request): Response
    {

        $queryBuilder = $entityManager->getRepository(DumpList::class)->createQueryBuilder('dumplist');
        $dataTable = $this->createDataTable(\App\DataTable\DumpList::class, $queryBuilder);

        return $this->render('base.html.twig', [
            'dumps' => $dataTable->createView(),
        ]);

    }
```

I am probably missing something :/
