### ISSUE TITLE
[Icon] Error using icon for ButtonActionType + Bootstrap theme

### ISSUE THREAD

**Issue by jc-beyer-tqgg** [Kreyu/data-table-bundle#202]
Hello !

I have an issue using the icon option for a ButtonActionType using the Bootstrap5 theme.

Error is
 `Block "icon" does not exist on any of the configured data table themes: "@KreyuDataTable/themes/bootstrap_5.html.twig"`

My config looks like this
```
kreyu_data_table:
  defaults:
    themes:
      - '@KreyuDataTable/themes/bootstrap_5.html.twig'
      - '@KreyuDataTable/themes/bootstrap_icons_webfont.html.twig'
```

It works when i use the base.html.twig template.
