### ISSUE TITLE
Custom column twig template problem

### ISSUE THREAD

**Issue by kris-sum** [Kreyu/data-table-bundle#72]
Hi,

Great package, i'm new to symfony (but not to php) and have been looking for a decent data table component to use and this is by far the best structured one! (thank you!)

I'm having a problem creating a new column type - following [the guide](https://data-table-bundle.swroblewski.pl/docs/components/columns.html#creating-column-types) , everything is fine except I can't get my twig template working. 

**I get the following exception:**

```
Block "column_link_with_row_data_value" on template "@KreyuDataTable/themes/base.html.twig" does not exist.
```

I have
```
{# templates/datatable/theme.html.twig #}

{% block column_link_with_row_data_value %}
    <a {% with { attr: { href, target }|merge(attr) } %}{{- block('attributes') -}}{% endwith %}>
        {{- block('column_text_value') -}}
    </a>
{% endblock %}
```

and
```
kreyu_data_table:
  defaults:
    themes:
      - '@KreyuDataTable/themes/bootstrap_5.html.twig'
      - 'datatable/theme.html.twig'
```

As a workaround, if I remove the bootstrap5 theme from `krey_data_table.yaml` and extend it in my twig template, it works fine.
